### ISSUE TITLE
Deleting files with used pngs too

### ISSUE THREAD

**Issue by fatinWasta** [onevcat/FengNiao#10] opened 2017-04-12 13:00 UTC
it shows me that how many unused files are there in my project, but it also contains files which are used. And once I run the command , all the respective unused image becomes red files. Maybe its only removing its reference.
Plz help.

**Comment by onevcat** [comment] 2017-04-13 13:32
@fatinWasta Can you give an example? FengNiao is searching for images used in your source file and UI files (xib, storyboard). All other images will be marked as non-used. If you have some images not referenced in source and UI files, but you need to keep it, you could add them (or the path of which) to the `--exclude` option.

**Comment by fatinWasta** [comment] 2017-04-13 13:55
@onevcat thank you for replying. 
its deleting files which I've already used in source file too. And there are total 237 files which are unused it's showing.

**Comment by onevcat** [comment] 2017-04-13 14:51
Can you tell me how did you use them in your source? (maybe some source code on using the images could be a help to point out the problem)

**Comment by fatinWasta** [comment] 2017-04-14 09:11
cell.iconImg.image = [UIImage imageNamed:@"train_blue.png"];

I just cross verified, the images are not removed, they are in project but still not showing.

**Comment by onevcat** [comment] 2017-04-18 01:32
@fatinWasta 

I'm sorry but I am not sure I could understand what you mean exactly.

You said you were using some code like this:

```
cell.iconImg.image = [UIImage imageNamed:@"train_blue.png"];
``` 

And the image named "train_blue.png" is not removed from your folder. That is correct right. FengNiao will not remove the images in using. 

But if the images are still there, it should be also referenced in your Xcode project file, since FengNiao will never try to modify your project file.

So I am not quite sure what happened here. Is it possible to create a demo project which could reproduce it? Thanks!

**Comment by fatinWasta** [comment] 2017-04-18 03:51
I'll try to reproduce this in demo project and let you know. :) 
thanks.

**Closed** 2018-01-31 03:27 UTC
